### PR TITLE
Set -e to ensure script doesn't fail silently

### LINKED ISSUE #1074: core-vpc-development-deployment ram share workflow fails silently
## Expected Behavior

Actions job fails when the script fails

## Actual Behavior

The ram share section failed silently and gave a green tick for the action.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Other information

This fix will probably need doing for the other vpc deployment workflows

### PR DESCRIPTION
**Pull request by davidkelliott**
Fixes #1074

### CODE REVIEW

File: scripts/member-account-ram-association.sh [hunk 1]
```diff
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
```
Comment (gfou-al) [inline scripts/member-account-ram-association.sh:3]: Looks good. Just to note, this article https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/ recommends the use of `set -Eeuo pipefail`. As stated in the above: `set -e` by itself is far from enough. We can further improve upon the behavior created by set -e by combining it with set -o pipefail.

**Review by gfou-al — APPROVED** [review]
I approve with a comment. Refer to the code comment for details.

**Review by gfou-al — APPROVED** [review]
looks good
